language: python
python:
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - pandoc

install: pip install tox

# http://stackoverflow.com/a/42309035
script: tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d . | sed -e 's/pypypy/pypy/')

after_failure: cat .tox/log/tox-*.log
